name: CI/CD NPM test Suit

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
      runs-on: ubuntu-latest
      # name: __BLANK 3__
      steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
      - run: npm run test
